use std::collections::HashMap;
use std::fs;
use std::io::{Read, Write};
use std::path::Path;
use serde::{Deserialize, Serialize};

#[derive(Debug, Clone)]
pub struct IniPreferences {
    pub sections: HashMap<String, HashMap<String, String>>,
    pub file_path: String,
}

#[derive(Debug)]
pub enum IniError {
    IoError(std::io::Error),
    ParseError(String),
}

impl From<std::io::Error> for IniError {
    fn from(error: std::io::Error) -> Self {
        IniError::IoError(error)
    }
}

impl std::fmt::Display for IniError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            IniError::IoError(e) => write!(f, "IO Error: {}", e),
            IniError::ParseError(msg) => write!(f, "Parse Error: {}", msg),
        }
    }
}

impl std::error::Error for IniError {}

impl IniPreferences {
    pub fn new(file_path: String) -> Self {
        let mut prefs = IniPreferences {
            sections: HashMap::new(),
            file_path,
        };

        // Create default sections
        prefs.add_section("General");
        prefs.add_section("Network");
        prefs.add_section("Display");
        prefs.add_section("Security");
        prefs.add_section("Privacy");
        prefs.add_section("Advanced");

        prefs
    }

    pub fn add_section(&mut self, section_name: &str) {
        self.sections.entry(section_name.to_string()).or_insert_with(HashMap::new);
    }

    pub fn set_value(&mut self, section: &str, key: &str, value: &str) {
        self.sections
            .entry(section.to_string())
            .or_insert_with(HashMap::new)
            .insert(key.to_string(), value.to_string());
    }

    pub fn get_value(&self, section: &str, key: &str) -> Option<String> {
        self.sections.get(section)
            .and_then(|section_map| section_map.get(key))
            .cloned()
    }

    pub fn get_bool(&self, section: &str, key: &str) -> bool {
        self.get_value(section, key)
            .map(|v| v.to_lowercase() == "true" || v == "1" || v.to_lowercase() == "yes" || v.to_lowercase() == "on")
            .unwrap_or(false)
    }

    pub fn get_int(&self, section: &str, key: &str) -> i32 {
        self.get_value(section, key)
            .and_then(|v| v.parse::<i32>().ok())
            .unwrap_or(0)
    }

    pub fn get_float(&self, section: &str, key: &str) -> f32 {
        self.get_value(section, key)
            .and_then(|v| v.parse::<f32>().ok())
            .unwrap_or(0.0)
    }

    pub fn get_string(&self, section: &str, key: &str) -> String {
        self.get_value(section, key).unwrap_or_default()
    }

    pub fn remove_value(&mut self, section: &str, key: &str) -> bool {
        if let Some(section_map) = self.sections.get_mut(section) {
            section_map.remove(key).is_some()
        } else {
            false
        }
    }

    pub fn remove_section(&mut self, section: &str) -> bool {
        self.sections.remove(section).is_some()
    }

    pub fn save_to_file(&self) -> Result<(), IniError> {
        // Create directory if it doesn't exist
        if let Some(parent) = Path::new(&self.file_path).parent() {
            fs::create_dir_all(parent)
                .map_err(|e| IniError::IoError(e))?;
        }

        let mut content = String::new();

        // Add a header comment
        content.push_str("; Retro1996 Browser Configuration File\n");
        content.push_str("; Generated by Retro1996 Browser v3.0\n");
        content.push_str("; Do not edit manually unless you know what you're doing!\n");
        content.push_str("\n");

        for (section_name, section_values) in &self.sections {
            content.push_str(&format!("[{}]\n", section_name));

            for (key, value) in section_values {
                // Escape special characters in values
                let escaped_value = value.replace("\\", "\\\\").replace("\n", "\\n");
                content.push_str(&format!("{}={}\n", key, escaped_value));
            }
            content.push_str("\n");
        }

        fs::write(&self.file_path, content)
            .map_err(|e| IniError::IoError(e))?;
        Ok(())
    }

    pub fn load_from_file(&mut self) -> Result<(), IniError> {
        if !Path::new(&self.file_path).exists() {
            // File doesn't exist, that's OK - we'll use defaults
            return Ok(());
        }

        let mut file = fs::File::open(&self.file_path)?;
        let mut content = String::new();
        file.read_to_string(&mut content)?;

        self.parse_ini_content(&content)?;
        Ok(())
    }

    fn parse_ini_content(&mut self, content: &str) -> Result<(), IniError> {
        let mut current_section = String::new();

        for (line_num, line) in content.lines().enumerate() {
            let line = line.trim();

            // Skip empty lines and comments
            if line.is_empty() || line.starts_with(';') || line.starts_with('#') {
                continue;
            }

            // Check for section header
            if line.starts_with('[') && line.ends_with(']') {
                let section_name = &line[1..line.len()-1].trim();
                if !section_name.is_empty() {
                    current_section = section_name.to_string();
                    self.add_section(&current_section);
                } else {
                    return Err(IniError::ParseError(format!("Empty section name at line {}", line_num + 1)));
                }
            } else if !current_section.is_empty() {
                // Parse key-value pair
                if let Some(eq_pos) = line.find('=') {
                    let key = line[..eq_pos].trim();
                    let value = line[eq_pos + 1..].trim();

                    // Unescape special characters
                    let unescaped_value = value.replace("\\n", "\n").replace("\\\\", "\\");

                    if !key.is_empty() {
                        self.set_value(&current_section, key, &unescaped_value);
                    } else {
                        return Err(IniError::ParseError(format!("Empty key at line {}", line_num + 1)));
                    }
                } else {
                    // Treat as a key with empty value
                    if !line.is_empty() {
                        self.set_value(&current_section, line, "");
                    }
                }
            } else {
                return Err(IniError::ParseError(format!("Key-value pair outside section at line {}", line_num + 1)));
            }
        }

        Ok(())
    }

    pub fn get_all_keys(&self, section: &str) -> Vec<String> {
        self.sections.get(section)
            .map(|section_map| section_map.keys().cloned().collect())
            .unwrap_or_default()
    }

    pub fn get_all_sections(&self) -> Vec<String> {
        self.sections.keys().cloned().collect()
    }

    pub fn clear(&mut self) {
        self.sections.clear();
    }

    pub fn merge_from_file(&mut self, other_file: &str) -> Result<(), IniError> {
        if !Path::new(other_file).exists() {
            return Err(IniError::IoError(std::io::Error::new(
                std::io::ErrorKind::NotFound,
                "File not found"
            )));
        }

        let mut other_prefs = IniPreferences::new(other_file.to_string());
        other_prefs.load_from_file()?;

        // Merge sections from other file into this one
        for (section_name, section_values) in other_prefs.sections {
            for (key, value) in section_values {
                self.set_value(&section_name, &key, &value);
            }
        }

        Ok(())
    }

    pub fn export_section(&self, section: &str) -> Option<String> {
        if let Some(section_values) = self.sections.get(section) {
            let mut content = format!("[{}]\n", section);
            for (key, value) in section_values {
                content.push_str(&format!("{}={}\n", key, value));
            }
            Some(content)
        } else {
            None
        }
    }

    pub fn load_defaults(&mut self) {
        // General settings
        self.set_value("General", "HomePage", "about:welcome");
        self.set_value("General", "StartupPage", "about:welcome");
        self.set_value("General", "Language", "en-US");
        self.set_value("General", "ShowMenuBar", "true");
        self.set_value("General", "ShowToolBar", "true");
        self.set_value("General", "ShowStatusBar", "true");
        self.set_value("General", "ShowBookmarksBar", "false");
        self.set_value("General", "ConfirmExit", "true");
        self.set_value("General", "SaveSession", "false");

        // Network settings
        self.set_value("Network", "ConnectionSpeed", "56k");
        self.set_value("Network", "MaxConnections", "4");
        self.set_value("Network", "Timeout", "30");
        self.set_value("Network", "UseProxy", "false");
        self.set_value("Network", "ProxyHost", "");
        self.set_value("Network", "ProxyPort", "8080");
        self.set_value("Network", "ProxyUsername", "");
        self.set_value("Network", "ProxyPassword", "");
        self.set_value("Network", "EnableCookies", "true");
        self.set_value("Network", "CookiePrompt", "false");
        self.set_value("Network", "AcceptThirdPartyCookies", "false");
        self.set_value("Network", "EnableReferrer", "true");
        self.set_value("Network", "EnableImages", "true");
        self.set_value("Network", "EnableAnimations", "true");
        self.set_value("Network", "EnableSounds", "true");
        self.set_value("Network", "EnableJava", "false");
        self.set_value("Network", "EnableJavaScript", "true");
        self.set_value("Network", "EnablePlugins", "false");

        // Display settings
        self.set_value("Display", "FontSize", "medium");
        self.set_value("Display", "FixedFontSize", "medium");
        self.set_value("Display", "MinimumFontSize", "8");
        self.set_value("Display", "AllowPagesToChoose", "true");
        self.set_value("Display", "OverridePageColors", "false");
        self.set_value("Display", "BackgroundColor", "#FFFFFF");
        self.set_value("Display", "TextColor", "#000000");
        self.set_value("Display", "LinkColor", "#0000FF");
        self.set_value("Display", "VisitedLinkColor", "#800080");
        self.set_value("Display", "ActiveLinkColor", "#FF0000");
        self.set_value("Display", "UseDocumentColors", "true");
        self.set_value("Display", "ShowAnimations", "true");
        self.set_value("Display", "SmoothScroll", "false");
        self.set_value("Display", "ShowPictures", "true");
        self.set_value("Display", "ShowToolTips", "true");
        self.set_value("Display", "ShowStatusText", "true");

        // Security settings
        self.set_value("Security", "EnableSecurityWarnings", "true");
        self.set_value("Security", "CheckForServerIdentity", "true");
        self.set_value("Security", "EnableJavaSecurity", "true");
        self.set_value("Security", "EnableJavaScriptSecurity", "false"); // 1996 browsers had minimal JS security
        self.set_value("Security", "EnablePluginSecurity", "true");

        // Privacy settings
        self.set_value("Privacy", "ClearHistoryOnExit", "false");
        self.set_value("Privacy", "ClearCookiesOnExit", "false");
        self.set_value("Privacy", "ClearCacheOnExit", "false");
        self.set_value("Privacy", "DoNotTrack", "false");

        // Advanced settings
        self.set_value("Advanced", "EnableCache", "true");
        self.set_value("Advanced", "CacheSize", "50"); // MB
        self.set_value("Advanced", "EnableDiskCache", "true");
        self.set_value("Advanced", "EnableMemoryCache", "true");
        self.set_value("Advanced", "MemoryCacheSize", "4"); // MB
        self.set_value("Advanced", "EnableBGSOUND", "true");
        self.set_value("Advanced", "EnableMarquee", "true");
        self.set_value("Advanced", "EnableBlink", "true");
        self.set_value("Advanced", "EnableVBScript", "false");
        self.set_value("Advanced", "EnableLiveConnect", "false");
        self.set_value("Advanced", "EnableRemoteScripting", "false");
        self.set_value("Advanced", "MaxScriptStatements", "100000");
        self.set_value("Advanced", "EnableImageAnimation", "true");
        self.set_value("Advanced", "AnimateImages", "all");
    }

    pub fn backup_to_file(&self, backup_path: &str) -> Result<(), IniError> {
        let content = self.export_all();
        fs::write(backup_path, content)
            .map_err(|e| IniError::IoError(e))
    }

    pub fn restore_from_backup(&mut self, backup_path: &str) -> Result<(), IniError> {
        if !Path::new(backup_path).exists() {
            return Err(IniError::IoError(std::io::Error::new(
                std::io::ErrorKind::NotFound,
                "Backup file not found"
            )));
        }

        let content = fs::read_to_string(backup_path)
            .map_err(|e| IniError::IoError(e))?;

        self.parse_ini_content(&content)?;
        Ok(())
    }

    pub fn export_all(&self) -> String {
        let mut content = String::new();

        // Add a header comment
        content.push_str("; Retro1996 Browser Configuration Backup\n");
        content.push_str("; Generated by Retro1996 Browser v3.0\n");
        content.push_str("\n");

        for (section_name, section_values) in &self.sections {
            content.push_str(&format!("[{}]\n", section_name));

            for (key, value) in section_values {
                content.push_str(&format!("{}={}\n", key, value));
            }
            content.push_str("\n");
        }

        content
    }

    pub fn validate_setting(&self, section: &str, key: &str, value: &str) -> Result<(), String> {
        match (section, key) {
            ("Network", "Timeout") => {
                if let Ok(timeout) = value.parse::<u32>() {
                    if timeout < 5 || timeout > 300 {
                        return Err("Timeout must be between 5 and 300 seconds".to_string());
                    }
                } else {
                    return Err("Timeout must be a number".to_string());
                }
            },
            ("Display", "MinimumFontSize") => {
                if let Ok(size) = value.parse::<u32>() {
                    if size < 1 || size > 72 {
                        return Err("Minimum font size must be between 1 and 72 pixels".to_string());
                    }
                } else {
                    return Err("Minimum font size must be a number".to_string());
                }
            },
            ("Advanced", "CacheSize") => {
                if let Ok(size) = value.parse::<u32>() {
                    if size < 1 || size > 1000 {
                        return Err("Cache size must be between 1 and 1000 MB".to_string());
                    }
                } else {
                    return Err("Cache size must be a number".to_string());
                }
            },
            _ => {} // Other settings don't have validation
        }

        Ok(())
    }

    pub fn set_and_validate(&mut self, section: &str, key: &str, value: &str) -> Result<(), String> {
        self.validate_setting(section, key, value)?;
        self.set_value(section, key, value);
        Ok(())
    }

    pub fn get_section_as_map(&self, section: &str) -> HashMap<String, String> {
        self.sections.get(section)
            .cloned()
            .unwrap_or_default()
    }

    pub fn import_from_registry(&mut self, registry_path: &str) -> Result<(), IniError> {
        // This is a placeholder for Windows registry import functionality
        // In a real implementation, this would read from the Windows registry
        // For now, we'll just return an error indicating it's not implemented
        Err(IniError::ParseError("Registry import not implemented in this version".to_string()))
    }

    pub fn export_to_registry(&self, registry_path: &str) -> Result<(), IniError> {
        // This is a placeholder for Windows registry export functionality
        // In a real implementation, this would write to the Windows registry
        // For now, we'll just return an error indicating it's not implemented
        Err(IniError::ParseError("Registry export not implemented in this version".to_string()))
    }

    pub fn migrate_from_old_version(&mut self, old_prefs: &IniPreferences) {
        // Migrate settings from an older version of the preferences
        for (section_name, section_values) in &old_prefs.sections {
            for (key, value) in section_values {
                // Only migrate if the setting doesn't already exist
                if self.get_value(section_name, key).is_none() {
                    self.set_value(section_name, key, value);
                }
            }
        }
    }

    pub fn get_preference_groups(&self) -> Vec<String> {
        // Return groups of related preferences for UI organization
        vec![
            "General".to_string(),
            "Display".to_string(),
            "Network".to_string(),
            "Security".to_string(),
            "Privacy".to_string(),
            "Advanced".to_string(),
        ]
    }

    pub fn reset_to_factory_defaults(&mut self) {
        self.sections.clear();
        self.load_defaults();
    }

    pub fn is_default_value(&self, section: &str, key: &str) -> bool {
        let current_value = self.get_value(section, key);
        if current_value.is_none() {
            return true; // No value set means default
        }

        // Compare with default value
        let mut default_prefs = IniPreferences::new("temp".to_string());
        default_prefs.load_defaults();
        let default_value = default_prefs.get_value(section, key);

        current_value == default_value
    }

    pub fn get_changed_preferences(&self) -> Vec<(String, String, String)> {
        // Return list of (section, key, value) for preferences that differ from defaults
        let mut default_prefs = IniPreferences::new("temp".to_string());
        default_prefs.load_defaults();

        let mut changed = Vec::new();

        for (section_name, section_values) in &self.sections {
            for (key, value) in section_values {
                let default_value = default_prefs.get_value(section_name, key);
                if default_value.as_ref() != Some(value) {
                    changed.push((section_name.clone(), key.clone(), value.clone()));
                }
            }
        }

        changed
    }

    pub fn apply_theme(&mut self, theme_name: &str) {
        match theme_name {
            "classic" => {
                self.set_value("Display", "BackgroundColor", "#FFFFFF");
                self.set_value("Display", "TextColor", "#000000");
                self.set_value("Display", "LinkColor", "#0000FF");
                self.set_value("Display", "VisitedLinkColor", "#800080");
                self.set_value("Display", "ActiveLinkColor", "#FF0000");
            },
            "retro" => {
                self.set_value("Display", "BackgroundColor", "#C0C0C0");
                self.set_value("Display", "TextColor", "#000000");
                self.set_value("Display", "LinkColor", "#000080");
                self.set_value("Display", "VisitedLinkColor", "#800000");
                self.set_value("Display", "ActiveLinkColor", "#FF0000");
            },
            "dark" => {
                self.set_value("Display", "BackgroundColor", "#000000");
                self.set_value("Display", "TextColor", "#FFFFFF");
                self.set_value("Display", "LinkColor", "#00FFFF");
                self.set_value("Display", "VisitedLinkColor", "#FF00FF");
                self.set_value("Display", "ActiveLinkColor", "#FFFF00");
            },
            _ => {} // Unknown theme, do nothing
        }
    }

    pub fn get_theme(&self) -> String {
        let bg_color = self.get_string("Display", "BackgroundColor");
        if bg_color == "#000000" {
            "dark".to_string()
        } else if bg_color == "#C0C0C0" {
            "retro".to_string()
        } else {
            "classic".to_string()
        }
    }

    pub fn export_to_legacy_format(&self) -> String {
        // Export in a format compatible with 1996-era applications
        let mut output = String::new();
        output.push_str("Retro1996 Browser Configuration File\n");
        output.push_str("Version 3.0\n");
        output.push_str("\n");

        for (section_name, section_values) in &self.sections {
            output.push_str(&format!("[{}]\n", section_name.to_uppercase()));

            for (key, value) in section_values {
                output.push_str(&format!("{}={}\n", key.to_uppercase(), value));
            }
            output.push_str("\n");
        }

        output
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use tempfile::NamedTempFile;
    use std::fs;

    #[test]
    fn test_ini_creation() {
        let temp_file = NamedTempFile::new().unwrap();
        let ini = IniPreferences::new(temp_file.path().to_str().unwrap().to_string());
        assert_eq!(ini.sections.len(), 6); // General, Network, Display, Security, Privacy, Advanced
    }

    #[test]
    fn test_set_and_get_value() {
        let temp_file = NamedTempFile::new().unwrap();
        let mut ini = IniPreferences::new(temp_file.path().to_str().unwrap().to_string());

        ini.set_value("General", "TestKey", "TestValue");
        assert_eq!(ini.get_string("General", "TestKey"), "TestValue");
    }

    #[test]
    fn test_get_bool() {
        let temp_file = NamedTempFile::new().unwrap();
        let mut ini = IniPreferences::new(temp_file.path().to_str().unwrap().to_string());

        ini.set_value("General", "BoolTrue", "true");
        ini.set_value("General", "BoolFalse", "false");
        ini.set_value("General", "BoolOne", "1");
        ini.set_value("General", "BoolZero", "0");

        assert!(ini.get_bool("General", "BoolTrue"));
        assert!(!ini.get_bool("General", "BoolFalse"));
        assert!(ini.get_bool("General", "BoolOne"));
        assert!(!ini.get_bool("General", "BoolZero"));
    }

    #[test]
    fn test_get_int() {
        let temp_file = NamedTempFile::new().unwrap();
        let mut ini = IniPreferences::new(temp_file.path().to_str().unwrap().to_string());

        ini.set_value("General", "IntValue", "42");
        assert_eq!(ini.get_int("General", "IntValue"), 42);
    }

    #[test]
    fn test_get_float() {
        let temp_file = NamedTempFile::new().unwrap();
        let mut ini = IniPreferences::new(temp_file.path().to_str().unwrap().to_string());

        ini.set_value("General", "FloatValue", "3.14");
        assert_eq!(ini.get_float("General", "FloatValue"), 3.14);
    }

    #[test]
    fn test_save_and_load() {
        let temp_file = NamedTempFile::new().unwrap();
        let mut ini = IniPreferences::new(temp_file.path().to_str().unwrap().to_string());

        // Set some values
        ini.set_value("General", "HomePage", "http://example.com");
        ini.set_value("Network", "Timeout", "60");
        ini.set_value("Display", "FontSize", "large");

        // Save to file
        ini.save_to_file().unwrap();

        // Load from file
        let mut ini2 = IniPreferences::new(temp_file.path().to_str().unwrap().to_string());
        ini2.load_from_file().unwrap();

        // Verify values
        assert_eq!(ini2.get_string("General", "HomePage"), "http://example.com");
        assert_eq!(ini2.get_int("Network", "Timeout"), 60);
        assert_eq!(ini2.get_string("Display", "FontSize"), "large");
    }

    #[test]
    fn test_section_operations() {
        let temp_file = NamedTempFile::new().unwrap();
        let mut ini = IniPreferences::new(temp_file.path().to_str().unwrap().to_string());

        // Add a section
        ini.add_section("CustomSection");
        assert!(ini.sections.contains_key("CustomSection"));

        // Remove a value
        ini.set_value("CustomSection", "KeyToRemove", "Value");
        assert!(ini.remove_value("CustomSection", "KeyToRemove"));
        assert!(!ini.remove_value("CustomSection", "NonExistentKey"));

        // Remove a section
        assert!(ini.remove_section("CustomSection"));
        assert!(!ini.remove_section("NonExistentSection"));
    }

    #[test]
    fn test_defaults() {
        let temp_file = NamedTempFile::new().unwrap();
        let mut ini = IniPreferences::new(temp_file.path().to_str().unwrap().to_string());

        // Load defaults
        ini.load_defaults();

        // Verify some default values
        assert_eq!(ini.get_string("General", "HomePage"), "about:welcome");
        assert_eq!(ini.get_string("Network", "ConnectionSpeed"), "56k");
        assert_eq!(ini.get_bool("Network", "EnableJavaScript"), true);
        assert_eq!(ini.get_string("Display", "BackgroundColor"), "#FFFFFF");
    }

    #[test]
    fn test_merge() {
        let temp_file1 = NamedTempFile::new().unwrap();
        let temp_file2 = NamedTempFile::new().unwrap();

        let mut ini1 = IniPreferences::new(temp_file1.path().to_str().unwrap().to_string());
        let mut ini2 = IniPreferences::new(temp_file2.path().to_str().unwrap().to_string());

        // Set different values in each
        ini1.set_value("General", "Setting1", "Value1");
        ini2.set_value("General", "Setting2", "Value2");

        // Save ini2 to file
        ini2.save_to_file().unwrap();

        // Merge ini2 into ini1
        ini1.merge_from_file(temp_file2.path().to_str().unwrap()).unwrap();

        // Verify both values exist in ini1
        assert_eq!(ini1.get_string("General", "Setting1"), "Value1");
        assert_eq!(ini1.get_string("General", "Setting2"), "Value2");
    }

    #[test]
    fn test_export_section() {
        let temp_file = NamedTempFile::new().unwrap();
        let mut ini = IniPreferences::new(temp_file.path().to_str().unwrap().to_string());

        ini.set_value("General", "Key1", "Value1");
        ini.set_value("General", "Key2", "Value2");

        let exported = ini.export_section("General").unwrap();
        assert!(exported.contains("[General]"));
        assert!(exported.contains("Key1=Value1"));
        assert!(exported.contains("Key2=Value2"));
    }

    #[test]
    fn test_get_all_keys_and_sections() {
        let temp_file = NamedTempFile::new().unwrap();
        let mut ini = IniPreferences::new(temp_file.path().to_str().unwrap().to_string());

        ini.set_value("General", "Key1", "Value1");
        ini.set_value("General", "Key2", "Value2");
        ini.set_value("Network", "Key3", "Value3");

        let keys = ini.get_all_keys("General");
        assert_eq!(keys.len(), 2);
        assert!(keys.contains(&"Key1".to_string()));
        assert!(keys.contains(&"Key2".to_string()));

        let sections = ini.get_all_sections();
        assert!(sections.contains(&"General".to_string()));
        assert!(sections.contains(&"Network".to_string()));
    }

    #[test]
    fn test_validation() {
        let temp_file = NamedTempFile::new().unwrap();
        let mut ini = IniPreferences::new(temp_file.path().to_str().unwrap().to_string());

        // Valid timeout
        assert!(ini.set_and_validate("Network", "Timeout", "60").is_ok());

        // Invalid timeout (too low)
        assert!(ini.set_and_validate("Network", "Timeout", "1").is_err());

        // Invalid timeout (not a number)
        assert!(ini.set_and_validate("Network", "Timeout", "abc").is_err());

        // Valid font size
        assert!(ini.set_and_validate("Display", "MinimumFontSize", "12").is_ok());

        // Invalid font size (too high)
        assert!(ini.set_and_validate("Display", "MinimumFontSize", "100").is_err());
    }

    #[test]
    fn test_theme_application() {
        let temp_file = NamedTempFile::new().unwrap();
        let mut ini = IniPreferences::new(temp_file.path().to_str().unwrap().to_string());

        // Apply classic theme
        ini.apply_theme("classic");
        assert_eq!(ini.get_string("Display", "BackgroundColor"), "#FFFFFF");

        // Apply retro theme
        ini.apply_theme("retro");
        assert_eq!(ini.get_string("Display", "BackgroundColor"), "#C0C0C0");

        // Apply dark theme
        ini.apply_theme("dark");
        assert_eq!(ini.get_string("Display", "BackgroundColor"), "#000000");
    }

    #[test]
    fn test_reset_to_defaults() {
        let temp_file = NamedTempFile::new().unwrap();
        let mut ini = IniPreferences::new(temp_file.path().to_str().unwrap().to_string());

        // Set a custom value
        ini.set_value("General", "HomePage", "http://custom.com");

        // Reset to defaults
        ini.reset_to_factory_defaults();

        // Verify it's back to default
        assert_eq!(ini.get_string("General", "HomePage"), "about:welcome");
    }

    #[test]
    fn test_is_default_value() {
        let temp_file = NamedTempFile::new().unwrap();
        let mut ini = IniPreferences::new(temp_file.path().to_str().unwrap().to_string());

        // Load defaults
        ini.load_defaults();

        // Check that default value returns true
        assert!(ini.is_default_value("General", "HomePage"));

        // Change value and check that it returns false
        ini.set_value("General", "HomePage", "http://changed.com");
        assert!(!ini.is_default_value("General", "HomePage"));
    }

    #[test]
    fn test_get_changed_preferences() {
        let temp_file = NamedTempFile::new().unwrap();
        let mut ini = IniPreferences::new(temp_file.path().to_str().unwrap().to_string());

        // Load defaults
        ini.load_defaults();

        // Change a value
        ini.set_value("General", "HomePage", "http://changed.com");

        // Get changed preferences
        let changed = ini.get_changed_preferences();
        assert_eq!(changed.len(), 1);
        assert_eq!(changed[0].0, "General"); // section
        assert_eq!(changed[0].1, "HomePage"); // key
        assert_eq!(changed[0].2, "http://changed.com"); // value
    }

    #[test]
    fn test_legacy_export_format() {
        let temp_file = NamedTempFile::new().unwrap();
        let mut ini = IniPreferences::new(temp_file.path().to_str().unwrap().to_string());

        ini.set_value("General", "HomePage", "http://example.com");

        let legacy_format = ini.export_to_legacy_format();
        assert!(legacy_format.contains("[GENERAL]"));
        assert!(legacy_format.contains("HOMEPAGE=http://example.com"));
    }
}